version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo apt-get update -y
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo build started on 'date'
      - mkdir -p /var/www/html
      - cp index.html /var/www/html
  post_build:
    commands:
      - echo Build completed on $(date)
artifacts:
  files:
    - '**/*'

